/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universityroomsys.gui;

import javax.swing.JOptionPane;
import universityroomsystem.University;
import urs.cards.Card;
import urs.cards.Roles.Role;

/**
 *
 * @author Toby
 */
public class EditUser extends javax.swing.JFrame {

    private University uniModel;
    private Card selectedUser;
    /**
     * Creates new form EditUser
     */
    public EditUser() {
        
        initComponents();
        
        
        
        Role[] roles = Role.values();
        
        for(Role r : roles){
            jcmbEditUserRole.addItem(r.name());
        }
    }
    public void setUniversity(University objTarget){
        uniModel = objTarget;
    }
    
    public void setSelectedUser(Card user) {
        this.selectedUser = user;
        jtxtEditUserName.setText(selectedUser.getName());
    }
    private void disposeForm(){
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblEditUserTitle = new javax.swing.JLabel();
        jlblEditUserName = new javax.swing.JLabel();
        jlblEditUserRole = new javax.swing.JLabel();
        jtxtEditUserName = new javax.swing.JTextField();
        jcmbEditUserRole = new javax.swing.JComboBox<>();
        jbtnEditUserConfirm = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblEditUserTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblEditUserTitle.setText("Edit User");

        jlblEditUserName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlblEditUserName.setText("Name:");

        jlblEditUserRole.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlblEditUserRole.setText("Role:");

        jtxtEditUserName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jcmbEditUserRole.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jcmbEditUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select..." }));

        jbtnEditUserConfirm.setText("Confirm");
        jbtnEditUserConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditUserConfirmActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblEditUserRole)
                                .addGap(18, 18, 18)
                                .addComponent(jcmbEditUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblEditUserName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtEditUserName))
                            .addComponent(jlblEditUserTitle)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtnEditUserConfirm)
                        .addGap(18, 18, 18)
                        .addComponent(Cancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblEditUserTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEditUserName)
                    .addComponent(jtxtEditUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEditUserRole)
                    .addComponent(jcmbEditUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEditUserConfirm)
                    .addComponent(Cancel))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEditUserConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditUserConfirmActionPerformed
        String name = null;
        String role = null;
        
        if(jtxtEditUserName.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a name", "Null field", JOptionPane.ERROR_MESSAGE);
        }
        else if(jcmbEditUserRole.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Please select a role", "Null field", JOptionPane.ERROR_MESSAGE);
        } else {
            role = (String)jcmbEditUserRole.getSelectedItem();
            name = jtxtEditUserName.getText();
            
            uniModel.editUser(selectedUser, name, role);
            
            disposeForm();
        }
    }//GEN-LAST:event_jbtnEditUserConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton jbtnEditUserConfirm;
    private javax.swing.JComboBox<String> jcmbEditUserRole;
    private javax.swing.JLabel jlblEditUserName;
    private javax.swing.JLabel jlblEditUserRole;
    private javax.swing.JLabel jlblEditUserTitle;
    private javax.swing.JTextField jtxtEditUserName;
    // End of variables declaration//GEN-END:variables
}
